singleServerConfig:
  address:
  - "redis://101.43.143.184:9001"
  - "redis://101.43.143.184:9002"
  - "redis://101.43.143.184:9003"
  - "redis://101.43.143.184:9004"
  - "redis://101.43.143.184:9005"
  - "redis://101.43.143.184:9006"
  password: null
  clientName: null
  database: 7 #?????????0~15
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
  #dnsMonitoring: false

threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"